### ISSUE TITLE
pretrainedmodels中的resnet101，resnet152

### ISSUE THREAD

**Issue by zepengF** [Trustworthy-AI-Group/PGN#1]
pretrainedmodels中的resnet101，resnet152是否为resnet_v1版本？我在incv3模型上生成对抗样本验证其在resnet101，resnet152上的迁移性时发现和论文中差距较大
![image](https://github.com/Trustworthy-AI-Group/PGN/assets/48851922/f89576dd-8152-46aa-90a2-4fb50c74a0d8)
![image](https://github.com/Trustworthy-AI-Group/PGN/assets/48851922/0b116fa0-f4c0-4af0-bd2a-eae1c9b6526d)

**Comment by Zhijin-Ge** [comment]
你好，现在挂在arxiv的版本不是最终版本，目前这个结果是将他们的均值和方差都设为[0.5,0.5,0.5]的结果，请稍后几天等待我们后续的更新结果，谢谢~
