### ISSUE TITLE
疑惑

### ISSUE THREAD

**Issue by sayhelloto1988** [Trustworthy-AI-Group/PGN#2]
您好，我对您的实验进行了复现，但是存在一些问题，PGN-SIM与您论文中的结果有点出入，您可以给一份您这个的代码吗？
![image](https://github.com/Trustworthy-AI-Group/PGN/assets/112956711/02bfff60-6cd3-4b64-9745-f0cfebd62be8)

![image](https://github.com/Trustworthy-AI-Group/PGN/assets/112956711/dc323a89-e154-4941-9f09-4c3528bc1f4b)

**Comment by Zhijin-Ge** [comment]
你好，我们的PGN_SIM代码和你复现的不太一样，你可以试一下我们的代码，谢谢：
![image](https://github.com/Trustworthy-AI-Group/PGN/assets/42350897/848d17eb-53d1-4209-8979-3b993c212b9d)
![image](https://github.com/Trustworthy-AI-Group/PGN/assets/42350897/56169421-5b64-4e49-93e6-df3d1cfeae96)

**Comment by sayhelloto1988** [comment]
> 你好，我们的PGN_SIM代码和你复现的不太一样，你可以试一下我们的代码，谢谢： ![image](https://user-images.githubusercontent.com/42350897/276074004-848d17eb-53d1-4209-8979-3b993c212b9d.png) ![image](https://user-images.githubusercontent.com/42350897/276075145-56169421-5b64-4e49-93e6-df3d1cfeae96.png)

十分感谢您的回复！！！谢谢
