### ISSUE TITLE
数据集问题

### ISSUE THREAD

**Issue by Truman168** [Trustworthy-AI-Group/PGN#4]
很高兴看到这么有趣想法的文章！！！我就是想请问，images是需要根据csv文件里面的下载链接下载，然后每张图片的命名方式是根据csv文件里面的imageid命名吗，我直接下载下来，运行的时候，会出现找不到图片的报错

**Comment by Zhijin-Ge** [comment]
感谢你关注我们的工作！本实验所用的数据集是来自[nips-17对抗竞赛](https://github.com/cleverhans-lab/cleverhans/tree/master/cleverhans_v3.1.0/examples/nips17_adversarial_competition/dataset)，这里面提供了这个数据集的详细细节。由于之前已经有人整理好了这部分数据集（如[SSA](https://github.com/yuyang-long/SSA)），因此只需要下载图片和对应的csv文件即可，而不需要再根据csv文件里面的链接下载了。希望这条回复能帮到你。

**Comment by Truman168** [comment]
十分感谢回复！！！
