### ISSUE TITLE
about ensemble model

### ISSUE THREAD

**Issue by Truman168** [Trustworthy-AI-Group/PGN#5]

**Comment by Truman168** [comment]
非常好的工作，但是我复现ensemble实验部分时，发现我的结果和论文中的有些差异，下面是我的代码
![image](https://github.com/Trustworthy-AI-Group/PGN/assets/144144824/af0d82db-6614-473e-909b-8c6e51348574)
![image](https://github.com/Trustworthy-AI-Group/PGN/assets/144144824/20fa9636-2045-4a45-b074-9d078147e729)

**Comment by Zhijin-Ge** [comment]
你好，感谢关注这篇工作！上面的代码看着感觉也没有问题，你可以尝试一下我写的这个函数。
![image](https://github.com/Trustworthy-AI-Group/PGN/assets/42350897/a786ba2f-d134-4aab-94a9-0fff02bad2bb)

还有一种情况是，加载的模型权重版本的问题，因为pytorch官方提供最新的模型权重鲁棒性更强一些，具体信息在[这里](https://pytorch.org/vision/stable/models.html)，有时候白盒攻击的成功率也会降低。这个在我们最近做的项目[TransferAttack](https://github.com/Trustworthy-AI-Group/TransferAttack/issues/45)中也有体现。

**Comment by Truman168** [comment]
> 你好，感谢关注这篇工作！上面的代码看着感觉也没有问题，你可以尝试一下我写的这个函数。 ![image](https://private-user-images.githubusercontent.com/42350897/329108926-a786ba2f-d134-4aab-94a9-0fff02bad2bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyMjM0MjksIm5iZiI6MTcxNTIyMzEyOSwicGF0aCI6Ii80MjM1MDg5Ny8zMjkxMDg5MjYtYTc4NmJhMmYtZDEzNC00YWFiLTk0YTktMGZmZjAyYmFkMmJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA5VDAyNTIwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyOWZkYjU3MzY4Y2QwYTZlNmQzYWE2MDMzMzMyYWVmNWNkNzVmY2RjMTU4NTliMTZlMjkyZGUzYzNhZWQxNDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mpTIh5zhxe2ArMJgYLffxnWcFGCOibc7Ca7_0_ATVnA)
> 
> 还有一种情况是，加载的模型权重版本的问题，因为pytorch官方提供最新的模型权重鲁棒性更强一些，具体信息在[这里](https://pytorch.org/vision/stable/models.html)，有时候白盒攻击的成功率也会降低。这个在我们最近做的项目[TransferAttack](https://github.com/Trustworthy-AI-Group/TransferAttack/issues/45)中也有体现。

感谢回复，代码看上去感觉一样，可能是模型的问题，我再试试，再次感谢回复！！！

**Comment by Zhijin-Ge** [comment]
这个是我刚才跑的结果，至少白盒攻击还是比较高的，你的结果是有些异常。
![image](https://github.com/Trustworthy-AI-Group/PGN/assets/42350897/ca19cd44-ca5c-4f8d-9eaa-d86e971b1c2d)

**Comment by Truman168** [comment]
> > 你好，感谢关注这篇工作！上面的代码看着感觉也没有问题，你可以尝试一下我写的这个函数。 ![image](https://private-user-images.githubusercontent.com/42350897/329108926-a786ba2f-d134-4aab-94a9-0fff02bad2bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyMjM0MjksIm5iZiI6MTcxNTIyMzEyOSwicGF0aCI6Ii80MjM1MDg5Ny8zMjkxMDg5MjYtYTc4NmJhMmYtZDEzNC00YWFiLTk0YTktMGZmZjAyYmFkMmJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA5VDAyNTIwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyOWZkYjU3MzY4Y2QwYTZlNmQzYWE2MDMzMzMyYWVmNWNkNzVmY2RjMTU4NTliMTZlMjkyZGUzYzNhZWQxNDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mpTIh5zhxe2ArMJgYLffxnWcFGCOibc7Ca7_0_ATVnA)
> > 还有一种情况是，加载的模型权重版本的问题，因为pytorch官方提供最新的模型权重鲁棒性更强一些，具体信息在[这里](https://pytorch.org/vision/stable/models.html)，有时候白盒攻击的成功率也会降低。这个在我们最近做的项目[TransferAttack](https://github.com/Trustworthy-AI-Group/TransferAttack/issues/45)中也有体现。
> 
> 感谢回复，代码看上去感觉一样，可能是模型的问题，我再试试，再次感谢回复！！！

我还想问一下，就是你的model1、model2、model3都是和single model一样的初始化方法吗，like this
![image](https://github.com/Trustworthy-AI-Group/PGN/assets/144144824/1390388b-25c1-4fc9-b5d0-a9aa28fdeb7e)

**Comment by Zhijin-Ge** [comment]
是的。
![image](https://github.com/Trustworthy-AI-Group/PGN/assets/42350897/76637e8f-37ab-4494-9d8c-252e33a3a371)

**Comment by Truman168** [comment]
> 是的。 ![image](https://private-user-images.githubusercontent.com/42350897/329112041-76637e8f-37ab-4494-9d8c-252e33a3a371.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyMjM5NTMsIm5iZiI6MTcxNTIyMzY1MywicGF0aCI6Ii80MjM1MDg5Ny8zMjkxMTIwNDEtNzY2MzdlOGYtMzdhYi00NDk0LTlkOGMtMjUyZTMzYTNhMzcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA5VDAzMDA1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2ZjQwNzBlZDhiNDUyNzFiNGQxMTk5YmM4NmRkYTQyNmFhMDk1YTY1YmI1ZDk1YzU3ZGM4M2FkMmZkZjBlZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QB1ofrGn8-IUXpmr9ra0BQyzZ_jLXgIY6EC_NcmVx4U)

好的，那我再试试，感谢回复！！！
