### ISSUE TITLE
about the dim

### ISSUE THREAD

**Issue by Truman168** [Trustworthy-AI-Group/PGN#6]
很高兴能看到这么新颖的思想，我有一个问题，就是我在复现与input transformation方法结合的时候，复现的结果要差十几个点，我也看了另一个回答，在结合的时候也按照那个顺序修改了(虽然结合的是DIM)，但是最终的结果还是有些差距，以下是我用DIM结合的代码，能恳请您指点一下吗，非常感谢！！！
![image](https://github.com/Trustworthy-AI-Group/PGN/assets/144144824/23abc395-5e66-4305-b9b4-690854a90438)
![image](https://github.com/Trustworthy-AI-Group/PGN/assets/144144824/fc920f7e-9c74-40ad-afa5-36aa83e6c4bb)

这是我跑出来的一个实验结果
![image](https://github.com/Trustworthy-AI-Group/PGN/assets/144144824/9d13a2f1-8e37-49ce-834d-b21056fbbe7a)

**Comment by Zhijin-Ge** [comment]
> 很高兴能看到这么新颖的思想，我有一个问题，就是我在复现与input transformation方法结合的时候，复现的结果要差十几个点，我也看了另一个回答，在结合的时候也按照那个顺序修改了(虽然结合的是DIM)，但是最终的结果还是有些差距，以下是我用DIM结合的代码，能恳请您指点一下吗，非常感谢！！！ ![image](https://private-user-images.githubusercontent.com/144144824/334391790-23abc395-5e66-4305-b9b4-690854a90438.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1Mjk5MzMsIm5iZiI6MTcxODUyOTYzMywicGF0aCI6Ii8xNDQxNDQ4MjQvMzM0MzkxNzkwLTIzYWJjMzk1LTVlNjYtNDMwNS1iOWI0LTY5MDg1NGE5MDQzOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNlQwOTIwMzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNWE0MDczZWExNDgwY2EzNTkzNzY3MDdlZmY4MTljOGZiZmE3M2E0MmVmYTliMDU3ZDU0NGExMzUwZDZlNDhjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.lhif0lHiXlp6CYRu0pjlJCelBKrfUIx-SpWsrz9z2lk) ![image](https://private-user-images.githubusercontent.com/144144824/334391943-fc920f7e-9c74-40ad-afa5-36aa83e6c4bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1Mjk5MzMsIm5iZiI6MTcxODUyOTYzMywicGF0aCI6Ii8xNDQxNDQ4MjQvMzM0MzkxOTQzLWZjOTIwZjdlLTljNzQtNDBhZC1hZmE1LTM2YWE4M2U2YzRiYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNlQwOTIwMzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YWI4Y2YwMDEwYmU4OTE5NGI3OWY5N2NkMjM0ZjE1NTMyOTQxZjZlYmQ3MGUwNmRkMWFhZGM0YjdlNjA3NmI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.051ZN34cx-rqQqnXI6PecnIG0xHJk5QsrL0oK8ppDQQ)
> 
> 这是我跑出来的一个实验结果 ![image](https://private-user-images.githubusercontent.com/144144824/334392810-9d13a2f1-8e37-49ce-834d-b21056fbbe7a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1Mjk5MzMsIm5iZiI6MTcxODUyOTYzMywicGF0aCI6Ii8xNDQxNDQ4MjQvMzM0MzkyODEwLTlkMTNhMmYxLThlMzctNDljZS04MzRkLWIyMTA1NmZiYmU3YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNlQwOTIwMzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNDBkMjA3NGVjZGVjMGQyZTMyODdlMzY2MTUyYTU3YjllZjViZDc4OGQ2ZTQyZDFhMTcyMGU1MGI5M2ZkMzk0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wmcSd5daNnwTLpdTcglD_CsW_WNAzW8ZIyrBt81o228)

你好，这个是我写的核心代码部分：
![image](https://github.com/Trustworthy-AI-Group/PGN/assets/42350897/1958b98f-e38a-47ce-b4d5-8f1da8d05f51)
DIM方法可以参考SSA里面的代码。
![image](https://github.com/Trustworthy-AI-Group/PGN/assets/42350897/a03e4634-486d-4dcc-981c-f24b411ff97b)
下面是跑的部分结果：
![image](https://github.com/Trustworthy-AI-Group/PGN/assets/42350897/920e13f1-ad04-4854-af7a-ec87389a5812)
希望能帮到你。

**Comment by Truman168** [comment]
好的非常感谢！！！！
